id = "astro-build.houston"
name = "Houston"
version = "0.0.1"
schema_version = 1
authors = ["Your Name <you@example.com>"]
description = "A theme featuring cool blues, minty greens, and soft purples"
repository = "https://github.com/withastro/"
